### ISSUE TITLE
xmlhttprequest需要onload,onerror,ontimeout怎么办

### ISSUE THREAD

**Issue by sirkay777** [leancloud/weapp-polyfill#4]
我在小程序里用的一个npm包依赖fetch，
我找到了github的fetch polyfill，里面依赖xmlhttprequest，
于是我找到了这里。
github的fetch里需要xmlhttprequest 有onload,onerror,ontimeout
https://github.com/github/fetch/blob/fcc4e1b48cfb5a2b1625fcd6eac06d954b00ccb6/fetch.js#L427-L444
我直接在successCallback里调用onload？有什么建议吗？
onload这种方式比较古老？所以你们没加上？我看在REQUEST_EVENTS里列出来了

**Comment by cuijiemmx** [comment]
用wx.request直接实现fetch

**Comment by leeyeh** [comment]
>xmlhttprequest 需要 onload,onerror,ontimeout

是有的。
